/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ChildrenSearchVO.as).
 */

package org.hil.core.model.vo.search {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class ChildrenSearchVOBase implements IExternalizable {

        private var _childCode:String;
        private var _childName:String;
        private var _communeId:Number;
        private var _dateOfBirthFrom:Date;
        private var _dateOfBirthTo:Date;
        private var _districtId:Number;
        private var _motherName:String;
        private var _provinceId:Number;
        private var _villageId:Number;

        public function set childCode(value:String):void {
            _childCode = value;
        }
        public function get childCode():String {
            return _childCode;
        }

        public function set childName(value:String):void {
            _childName = value;
        }
        public function get childName():String {
            return _childName;
        }

        public function set communeId(value:Number):void {
            _communeId = value;
        }
        public function get communeId():Number {
            return _communeId;
        }

        public function set dateOfBirthFrom(value:Date):void {
            _dateOfBirthFrom = value;
        }
        public function get dateOfBirthFrom():Date {
            return _dateOfBirthFrom;
        }

        public function set dateOfBirthTo(value:Date):void {
            _dateOfBirthTo = value;
        }
        public function get dateOfBirthTo():Date {
            return _dateOfBirthTo;
        }

        public function set districtId(value:Number):void {
            _districtId = value;
        }
        public function get districtId():Number {
            return _districtId;
        }

        public function set motherName(value:String):void {
            _motherName = value;
        }
        public function get motherName():String {
            return _motherName;
        }

        public function set provinceId(value:Number):void {
            _provinceId = value;
        }
        public function get provinceId():Number {
            return _provinceId;
        }

        public function set villageId(value:Number):void {
            _villageId = value;
        }
        public function get villageId():Number {
            return _villageId;
        }

        public function readExternal(input:IDataInput):void {
            _childCode = input.readObject() as String;
            _childName = input.readObject() as String;
            _communeId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _dateOfBirthFrom = input.readObject() as Date;
            _dateOfBirthTo = input.readObject() as Date;
            _districtId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _motherName = input.readObject() as String;
            _provinceId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _villageId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_childCode);
            output.writeObject(_childName);
            output.writeObject(_communeId);
            output.writeObject(_dateOfBirthFrom);
            output.writeObject(_dateOfBirthTo);
            output.writeObject(_districtId);
            output.writeObject(_motherName);
            output.writeObject(_provinceId);
            output.writeObject(_villageId);
        }
    }
}