/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.hil.core.model {
	import org.hil.core.util.StringUtils;
	
    [Bindable]
    [RemoteClass(alias="org.hil.core.model.ChildrenUnder1")]
    public class ChildrenUnder1 extends ChildrenUnder1Base {
		private var _strTotalChildrenUnder1:String;
		
		public function get strTotalChildrenUnder1():String {
			if (isNaN(this.totalChildrenUnder1))
				return ""
			else
				return String(this.totalChildrenUnder1);
		}		
		
		public function set strTotalChildrenUnder1(_inputstr:String):void {
			_strTotalChildrenUnder1 = _inputstr;
			if (StringUtils.trim(_inputstr) == "") {
				this.totalChildrenUnder1 = Number.NaN;		
			} else
				this.totalChildrenUnder1 = Number(_inputstr);
		}
		
    }
}