/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.hil.core.model {
	import org.hil.core.util.StringUtils;
    [Bindable]
    [RemoteClass(alias="org.hil.core.model.GeneralReportData")]
    public class GeneralReportData extends GeneralReportDataBase {
		private var _strAmountOfTetanusProtection:String;
		private var _strTotalNormalCases:String;
		private var _strTotalSeriousCases:String;
		
		public function get strAmountOfTetanusProtection():String {
			if (isNaN(this.amountOfTetanusProtection))
				return ""
			else
				return String(this.amountOfTetanusProtection);
		}
		
		
		public function set strAmountOfTetanusProtection(_inputstr:String):void {
			_strAmountOfTetanusProtection = _inputstr;
			if (StringUtils.trim(_inputstr) == "") {
				this.amountOfTetanusProtection = Number.NaN;		
			} else
				this.amountOfTetanusProtection = Number(_inputstr);
		}
		
		public function get strTotalNormalCases():String {
			if (isNaN(this.totalNormalCases))
				return ""
			else
				return String(this.totalNormalCases);
		}		
		
		public function set strTotalNormalCases(_inputstr:String):void {
			_strTotalNormalCases = _inputstr;
			if (StringUtils.trim(_inputstr) == "") {
				this.totalNormalCases = Number.NaN;		
			} else
				this.totalNormalCases = Number(_inputstr);
		}
		
		public function get strTotalSeriousCases():String {
			if (isNaN(this.totalSeriousCases))
				return ""
			else
				return String(this.totalSeriousCases);
		}		
		
		public function set strTotalSeriousCases(_inputstr:String):void {
			_strTotalSeriousCases = _inputstr;
			if (StringUtils.trim(_inputstr) == "") {
				this.totalSeriousCases = Number.NaN;		
			} else
				this.totalSeriousCases = Number(_inputstr);
		}
    }
}