/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Region.as).
 */

package org.hil.core.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.meta;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class RegionBase extends AbstractEntity {

        private var _regionName:String;

        public function set regionName(value:String):void {
            _regionName = value;
        }
        public function get regionName():String {
            return _regionName;
        }

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:RegionBase = RegionBase(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
               em.meta_mergeExternal(src._regionName, _regionName, null, this, 'regionName', function setter(o:*):void{_regionName = o as String}, false);
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _regionName = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject((_regionName is IPropertyHolder) ? IPropertyHolder(_regionName).object : _regionName);
            }
        }
    }
}
