/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.hil.core.model {

    [Bindable]
    [RemoteClass(alias="org.hil.core.model.SystemUser")]
    public class SystemUser extends SystemUserBase {
    }
}