/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SystemUser.as).
 */

package org.hil.core.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.meta;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class SystemUserBase extends AbstractEntity {

        private var _address:String;
        private var _commune:Commune;
        private var _dateOfBirth:Date;
        private var _fullName:String;
        private var _gender:Boolean;
        private var _mobile:String;
        private var _systemAccount:SystemAccount;
        private var _tel:String;

        public function set address(value:String):void {
            _address = value;
        }
        public function get address():String {
            return _address;
        }

        public function set commune(value:Commune):void {
            _commune = value;
        }
        public function get commune():Commune {
            return _commune;
        }

        public function set dateOfBirth(value:Date):void {
            _dateOfBirth = value;
        }
        public function get dateOfBirth():Date {
            return _dateOfBirth;
        }

        public function set fullName(value:String):void {
            _fullName = value;
        }
        public function get fullName():String {
            return _fullName;
        }

        public function set gender(value:Boolean):void {
            _gender = value;
        }
        public function get gender():Boolean {
            return _gender;
        }

        public function set mobile(value:String):void {
            _mobile = value;
        }
        public function get mobile():String {
            return _mobile;
        }

        public function set systemAccount(value:SystemAccount):void {
            _systemAccount = value;
        }
        public function get systemAccount():SystemAccount {
            return _systemAccount;
        }

        public function set tel(value:String):void {
            _tel = value;
        }
        public function get tel():String {
            return _tel;
        }

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:SystemUserBase = SystemUserBase(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
               em.meta_mergeExternal(src._address, _address, null, this, 'address', function setter(o:*):void{_address = o as String}, false);
               em.meta_mergeExternal(src._commune, _commune, null, this, 'commune', function setter(o:*):void{_commune = o as Commune}, false);
               em.meta_mergeExternal(src._dateOfBirth, _dateOfBirth, null, this, 'dateOfBirth', function setter(o:*):void{_dateOfBirth = o as Date}, false);
               em.meta_mergeExternal(src._fullName, _fullName, null, this, 'fullName', function setter(o:*):void{_fullName = o as String}, false);
               em.meta_mergeExternal(src._gender, _gender, null, this, 'gender', function setter(o:*):void{_gender = o as Boolean}, false);
               em.meta_mergeExternal(src._mobile, _mobile, null, this, 'mobile', function setter(o:*):void{_mobile = o as String}, false);
               em.meta_mergeExternal(src._systemAccount, _systemAccount, null, this, 'systemAccount', function setter(o:*):void{_systemAccount = o as SystemAccount}, false);
               em.meta_mergeExternal(src._tel, _tel, null, this, 'tel', function setter(o:*):void{_tel = o as String}, false);
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _address = input.readObject() as String;
                _commune = input.readObject() as Commune;
                _dateOfBirth = input.readObject() as Date;
                _fullName = input.readObject() as String;
                _gender = input.readObject() as Boolean;
                _mobile = input.readObject() as String;
                _systemAccount = input.readObject() as SystemAccount;
                _tel = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject((_address is IPropertyHolder) ? IPropertyHolder(_address).object : _address);
                output.writeObject((_commune is IPropertyHolder) ? IPropertyHolder(_commune).object : _commune);
                output.writeObject((_dateOfBirth is IPropertyHolder) ? IPropertyHolder(_dateOfBirth).object : _dateOfBirth);
                output.writeObject((_fullName is IPropertyHolder) ? IPropertyHolder(_fullName).object : _fullName);
                output.writeObject((_gender is IPropertyHolder) ? IPropertyHolder(_gender).object : _gender);
                output.writeObject((_mobile is IPropertyHolder) ? IPropertyHolder(_mobile).object : _mobile);
                output.writeObject((_systemAccount is IPropertyHolder) ? IPropertyHolder(_systemAccount).object : _systemAccount);
                output.writeObject((_tel is IPropertyHolder) ? IPropertyHolder(_tel).object : _tel);
            }
        }
    }
}
