/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SystemRole.as).
 */

package org.hil.core.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.meta;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class SystemRoleBase extends AbstractEntity {

        private var _description:String;
        private var _roleName:String;

        public function set description(value:String):void {
            _description = value;
        }
        public function get description():String {
            return _description;
        }

        public function set roleName(value:String):void {
            _roleName = value;
        }
        public function get roleName():String {
            return _roleName;
        }

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:SystemRoleBase = SystemRoleBase(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
               em.meta_mergeExternal(src._description, _description, null, this, 'description', function setter(o:*):void{_description = o as String}, false);
               em.meta_mergeExternal(src._roleName, _roleName, null, this, 'roleName', function setter(o:*):void{_roleName = o as String}, false);
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _description = input.readObject() as String;
                _roleName = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject((_description is IPropertyHolder) ? IPropertyHolder(_description).object : _description);
                output.writeObject((_roleName is IPropertyHolder) ? IPropertyHolder(_roleName).object : _roleName);
            }
        }
    }
}
