/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Village.as).
 */

package org.hil.core.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.meta;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class VillageBase extends AbstractEntity {

        private var _commune:Commune;
        private var _notes:String;
        private var _villageId:String;
        private var _villageName:String;

        public function set commune(value:Commune):void {
            _commune = value;
        }
        public function get commune():Commune {
            return _commune;
        }

        public function set notes(value:String):void {
            _notes = value;
        }
        public function get notes():String {
            return _notes;
        }

        public function set villageId(value:String):void {
            _villageId = value;
        }
        public function get villageId():String {
            return _villageId;
        }

        public function set villageName(value:String):void {
            _villageName = value;
        }
        public function get villageName():String {
            return _villageName;
        }

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:VillageBase = VillageBase(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
               em.meta_mergeExternal(src._commune, _commune, null, this, 'commune', function setter(o:*):void{_commune = o as Commune}, false);
               em.meta_mergeExternal(src._notes, _notes, null, this, 'notes', function setter(o:*):void{_notes = o as String}, false);
               em.meta_mergeExternal(src._villageId, _villageId, null, this, 'villageId', function setter(o:*):void{_villageId = o as String}, false);
               em.meta_mergeExternal(src._villageName, _villageName, null, this, 'villageName', function setter(o:*):void{_villageName = o as String}, false);
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _commune = input.readObject() as Commune;
                _notes = input.readObject() as String;
                _villageId = input.readObject() as String;
                _villageName = input.readObject() as String;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject((_commune is IPropertyHolder) ? IPropertyHolder(_commune).object : _commune);
                output.writeObject((_notes is IPropertyHolder) ? IPropertyHolder(_notes).object : _notes);
                output.writeObject((_villageId is IPropertyHolder) ? IPropertyHolder(_villageId).object : _villageId);
                output.writeObject((_villageName is IPropertyHolder) ? IPropertyHolder(_villageName).object : _villageName);
            }
        }
    }
}
