/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Mon Mar 09 10:40:42 PDT 2009.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.hil.core.model.util {

    [Bindable]
    [RemoteClass(alias="org.hil.core.model.util.PageableList")]
    public class PageableList extends PageableListBase {
    }
}