/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.hil.core.model.vo {

    [Bindable]
    [RemoteClass(alias="org.hil.core.model.vo.ChildrenDuePrintVO")]
    public class ChildrenDuePrintVO extends ChildrenDuePrintVOBase {
    }
}