/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ChildrenPrintVO.as).
 */

package org.hil.core.model.vo {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class ChildrenPrintVOBase implements IExternalizable {

        private var _BCG:String;
        private var _DPT_VGB_Hib1:String;
        private var _DPT_VGB_Hib2:String;
        private var _DPT_VGB_Hib3:String;
        private var _OPV1:String;
        private var _OPV2:String;
        private var _OPV3:String;
        private var _VGB:String;
        private var _caretakerBirthYear:Number;
        private var _caretakerID:String;
        private var _caretakerMobile:String;
        private var _caretakerName:String;
        private var _childCode:String;
        private var _communeName:String;
        private var _currentCaretaker:Number;
        private var _dateOfBirth:Date;
        private var _fatherBirthYear:Number;
        private var _fatherID:String;
        private var _fatherMobile:String;
        private var _fatherName:String;
        private var _fullName:String;
        private var _gender:Boolean;
        private var _measles1:String;
        private var _motherBirthYear:Number;
        private var _motherID:String;
        private var _motherMobile:String;
        private var _motherName:String;
        private var _villageName:String;

        public function set BCG(value:String):void {
            _BCG = value;
        }
        public function get BCG():String {
            return _BCG;
        }

        public function set DPT_VGB_Hib1(value:String):void {
            _DPT_VGB_Hib1 = value;
        }
        public function get DPT_VGB_Hib1():String {
            return _DPT_VGB_Hib1;
        }

        public function set DPT_VGB_Hib2(value:String):void {
            _DPT_VGB_Hib2 = value;
        }
        public function get DPT_VGB_Hib2():String {
            return _DPT_VGB_Hib2;
        }

        public function set DPT_VGB_Hib3(value:String):void {
            _DPT_VGB_Hib3 = value;
        }
        public function get DPT_VGB_Hib3():String {
            return _DPT_VGB_Hib3;
        }

        public function set OPV1(value:String):void {
            _OPV1 = value;
        }
        public function get OPV1():String {
            return _OPV1;
        }

        public function set OPV2(value:String):void {
            _OPV2 = value;
        }
        public function get OPV2():String {
            return _OPV2;
        }

        public function set OPV3(value:String):void {
            _OPV3 = value;
        }
        public function get OPV3():String {
            return _OPV3;
        }

        public function set VGB(value:String):void {
            _VGB = value;
        }
        public function get VGB():String {
            return _VGB;
        }

        public function set caretakerBirthYear(value:Number):void {
            _caretakerBirthYear = value;
        }
        public function get caretakerBirthYear():Number {
            return _caretakerBirthYear;
        }

        public function set caretakerID(value:String):void {
            _caretakerID = value;
        }
        public function get caretakerID():String {
            return _caretakerID;
        }

        public function set caretakerMobile(value:String):void {
            _caretakerMobile = value;
        }
        public function get caretakerMobile():String {
            return _caretakerMobile;
        }

        public function set caretakerName(value:String):void {
            _caretakerName = value;
        }
        public function get caretakerName():String {
            return _caretakerName;
        }

        public function set childCode(value:String):void {
            _childCode = value;
        }
        public function get childCode():String {
            return _childCode;
        }

        public function set communeName(value:String):void {
            _communeName = value;
        }
        public function get communeName():String {
            return _communeName;
        }

        public function set currentCaretaker(value:Number):void {
            _currentCaretaker = value;
        }
        public function get currentCaretaker():Number {
            return _currentCaretaker;
        }

        public function set dateOfBirth(value:Date):void {
            _dateOfBirth = value;
        }
        public function get dateOfBirth():Date {
            return _dateOfBirth;
        }

        public function set fatherBirthYear(value:Number):void {
            _fatherBirthYear = value;
        }
        public function get fatherBirthYear():Number {
            return _fatherBirthYear;
        }

        public function set fatherID(value:String):void {
            _fatherID = value;
        }
        public function get fatherID():String {
            return _fatherID;
        }

        public function set fatherMobile(value:String):void {
            _fatherMobile = value;
        }
        public function get fatherMobile():String {
            return _fatherMobile;
        }

        public function set fatherName(value:String):void {
            _fatherName = value;
        }
        public function get fatherName():String {
            return _fatherName;
        }

        public function set fullName(value:String):void {
            _fullName = value;
        }
        public function get fullName():String {
            return _fullName;
        }

        public function set gender(value:Boolean):void {
            _gender = value;
        }
        public function get gender():Boolean {
            return _gender;
        }

        public function set measles1(value:String):void {
            _measles1 = value;
        }
        public function get measles1():String {
            return _measles1;
        }

        public function set motherBirthYear(value:Number):void {
            _motherBirthYear = value;
        }
        public function get motherBirthYear():Number {
            return _motherBirthYear;
        }

        public function set motherID(value:String):void {
            _motherID = value;
        }
        public function get motherID():String {
            return _motherID;
        }

        public function set motherMobile(value:String):void {
            _motherMobile = value;
        }
        public function get motherMobile():String {
            return _motherMobile;
        }

        public function set motherName(value:String):void {
            _motherName = value;
        }
        public function get motherName():String {
            return _motherName;
        }

        public function set villageName(value:String):void {
            _villageName = value;
        }
        public function get villageName():String {
            return _villageName;
        }

        public function readExternal(input:IDataInput):void {
            _BCG = input.readObject() as String;
            _DPT_VGB_Hib1 = input.readObject() as String;
            _DPT_VGB_Hib2 = input.readObject() as String;
            _DPT_VGB_Hib3 = input.readObject() as String;
            _OPV1 = input.readObject() as String;
            _OPV2 = input.readObject() as String;
            _OPV3 = input.readObject() as String;
            _VGB = input.readObject() as String;
            _caretakerBirthYear = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _caretakerID = input.readObject() as String;
            _caretakerMobile = input.readObject() as String;
            _caretakerName = input.readObject() as String;
            _childCode = input.readObject() as String;
            _communeName = input.readObject() as String;
            _currentCaretaker = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _dateOfBirth = input.readObject() as Date;
            _fatherBirthYear = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _fatherID = input.readObject() as String;
            _fatherMobile = input.readObject() as String;
            _fatherName = input.readObject() as String;
            _fullName = input.readObject() as String;
            _gender = input.readObject() as Boolean;
            _measles1 = input.readObject() as String;
            _motherBirthYear = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _motherID = input.readObject() as String;
            _motherMobile = input.readObject() as String;
            _motherName = input.readObject() as String;
            _villageName = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_BCG);
            output.writeObject(_DPT_VGB_Hib1);
            output.writeObject(_DPT_VGB_Hib2);
            output.writeObject(_DPT_VGB_Hib3);
            output.writeObject(_OPV1);
            output.writeObject(_OPV2);
            output.writeObject(_OPV3);
            output.writeObject(_VGB);
            output.writeObject(_caretakerBirthYear);
            output.writeObject(_caretakerID);
            output.writeObject(_caretakerMobile);
            output.writeObject(_caretakerName);
            output.writeObject(_childCode);
            output.writeObject(_communeName);
            output.writeObject(_currentCaretaker);
            output.writeObject(_dateOfBirth);
            output.writeObject(_fatherBirthYear);
            output.writeObject(_fatherID);
            output.writeObject(_fatherMobile);
            output.writeObject(_fatherName);
            output.writeObject(_fullName);
            output.writeObject(_gender);
            output.writeObject(_measles1);
            output.writeObject(_motherBirthYear);
            output.writeObject(_motherID);
            output.writeObject(_motherMobile);
            output.writeObject(_motherName);
            output.writeObject(_villageName);
        }
    }
}