/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ChildrenVaccinatedInLocationVO.as).
 */

package org.hil.core.model.vo {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class ChildrenVaccinatedInLocationVOBase implements IExternalizable {

        private var _childCode:String;
        private var _communeName:String;
        private var _dateOfBirth:Date;
        private var _dateOfImmunization:Date;
        private var _fullName:String;
        private var _gender:Boolean;
        private var _id:Number;
        private var _motherName:String;
        private var _otherLocation:Number;
        private var _vaccinatedCommune:String;
        private var _villageName:String;

        public function set childCode(value:String):void {
            _childCode = value;
        }
        public function get childCode():String {
            return _childCode;
        }

        public function set communeName(value:String):void {
            _communeName = value;
        }
        public function get communeName():String {
            return _communeName;
        }

        public function set dateOfBirth(value:Date):void {
            _dateOfBirth = value;
        }
        public function get dateOfBirth():Date {
            return _dateOfBirth;
        }

        public function set dateOfImmunization(value:Date):void {
            _dateOfImmunization = value;
        }
        public function get dateOfImmunization():Date {
            return _dateOfImmunization;
        }

        public function set fullName(value:String):void {
            _fullName = value;
        }
        public function get fullName():String {
            return _fullName;
        }

        public function set gender(value:Boolean):void {
            _gender = value;
        }
        public function get gender():Boolean {
            return _gender;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set motherName(value:String):void {
            _motherName = value;
        }
        public function get motherName():String {
            return _motherName;
        }

        public function set otherLocation(value:Number):void {
            _otherLocation = value;
        }
        public function get otherLocation():Number {
            return _otherLocation;
        }

        public function set vaccinatedCommune(value:String):void {
            _vaccinatedCommune = value;
        }
        public function get vaccinatedCommune():String {
            return _vaccinatedCommune;
        }

        public function set villageName(value:String):void {
            _villageName = value;
        }
        public function get villageName():String {
            return _villageName;
        }

        public function readExternal(input:IDataInput):void {
            _childCode = input.readObject() as String;
            _communeName = input.readObject() as String;
            _dateOfBirth = input.readObject() as Date;
            _dateOfImmunization = input.readObject() as Date;
            _fullName = input.readObject() as String;
            _gender = input.readObject() as Boolean;
            _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _motherName = input.readObject() as String;
            _otherLocation = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _vaccinatedCommune = input.readObject() as String;
            _villageName = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_childCode);
            output.writeObject(_communeName);
            output.writeObject(_dateOfBirth);
            output.writeObject(_dateOfImmunization);
            output.writeObject(_fullName);
            output.writeObject(_gender);
            output.writeObject(_id);
            output.writeObject(_motherName);
            output.writeObject(_otherLocation);
            output.writeObject(_vaccinatedCommune);
            output.writeObject(_villageName);
        }
    }
}