/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ChildrenDuePrintVO.as).
 */

package org.hil.core.model.vo {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class ChildrenDuePrintVOBase implements IExternalizable {

        private var _address:String;
        private var _cId:Number;
        private var _caretakerBirthYear:Number;
        private var _caretakerID:String;
        private var _caretakerMobile:String;
        private var _caretakerName:String;
        private var _childCode:String;
        private var _childId:Number;
        private var _communeName:String;
        private var _currentCaretaker:Number;
        private var _dId:Number;
        private var _dateOfBirth:Date;
        private var _districtName:String;
        private var _fatherBirthYear:Number;
        private var _fatherID:String;
        private var _fatherMobile:String;
        private var _fatherName:String;
        private var _fullName:String;
        private var _gender:Boolean;
        private var _listVaccines:ListCollectionView;
        private var _locked:Boolean;
        private var _motherBirthYear:Number;
        private var _motherID:String;
        private var _motherMobile:String;
        private var _motherName:String;
        private var _pId:Number;
        private var _provinceName:String;
        private var _residen:String;
        private var _vId:Number;
        private var _vaccinationDue:String;
        private var _vaccinationOverdue:String;
        private var _vaccines:String;

        public function set address(value:String):void {
            _address = value;
        }
        public function get address():String {
            return _address;
        }

        public function set cId(value:Number):void {
            _cId = value;
        }
        public function get cId():Number {
            return _cId;
        }

        public function set caretakerBirthYear(value:Number):void {
            _caretakerBirthYear = value;
        }
        public function get caretakerBirthYear():Number {
            return _caretakerBirthYear;
        }

        public function set caretakerID(value:String):void {
            _caretakerID = value;
        }
        public function get caretakerID():String {
            return _caretakerID;
        }

        public function set caretakerMobile(value:String):void {
            _caretakerMobile = value;
        }
        public function get caretakerMobile():String {
            return _caretakerMobile;
        }

        public function set caretakerName(value:String):void {
            _caretakerName = value;
        }
        public function get caretakerName():String {
            return _caretakerName;
        }

        public function set childCode(value:String):void {
            _childCode = value;
        }
        public function get childCode():String {
            return _childCode;
        }

        public function set childId(value:Number):void {
            _childId = value;
        }
        public function get childId():Number {
            return _childId;
        }

        public function set communeName(value:String):void {
            _communeName = value;
        }
        public function get communeName():String {
            return _communeName;
        }

        public function set currentCaretaker(value:Number):void {
            _currentCaretaker = value;
        }
        public function get currentCaretaker():Number {
            return _currentCaretaker;
        }

        public function set dId(value:Number):void {
            _dId = value;
        }
        public function get dId():Number {
            return _dId;
        }

        public function set dateOfBirth(value:Date):void {
            _dateOfBirth = value;
        }
        public function get dateOfBirth():Date {
            return _dateOfBirth;
        }

        public function set districtName(value:String):void {
            _districtName = value;
        }
        public function get districtName():String {
            return _districtName;
        }

        public function set fatherBirthYear(value:Number):void {
            _fatherBirthYear = value;
        }
        public function get fatherBirthYear():Number {
            return _fatherBirthYear;
        }

        public function set fatherID(value:String):void {
            _fatherID = value;
        }
        public function get fatherID():String {
            return _fatherID;
        }

        public function set fatherMobile(value:String):void {
            _fatherMobile = value;
        }
        public function get fatherMobile():String {
            return _fatherMobile;
        }

        public function set fatherName(value:String):void {
            _fatherName = value;
        }
        public function get fatherName():String {
            return _fatherName;
        }

        public function set fullName(value:String):void {
            _fullName = value;
        }
        public function get fullName():String {
            return _fullName;
        }

        public function set gender(value:Boolean):void {
            _gender = value;
        }
        public function get gender():Boolean {
            return _gender;
        }

        public function set listVaccines(value:ListCollectionView):void {
            _listVaccines = value;
        }
        public function get listVaccines():ListCollectionView {
            return _listVaccines;
        }

        public function set locked(value:Boolean):void {
            _locked = value;
        }
        public function get locked():Boolean {
            return _locked;
        }

        public function set motherBirthYear(value:Number):void {
            _motherBirthYear = value;
        }
        public function get motherBirthYear():Number {
            return _motherBirthYear;
        }

        public function set motherID(value:String):void {
            _motherID = value;
        }
        public function get motherID():String {
            return _motherID;
        }

        public function set motherMobile(value:String):void {
            _motherMobile = value;
        }
        public function get motherMobile():String {
            return _motherMobile;
        }

        public function set motherName(value:String):void {
            _motherName = value;
        }
        public function get motherName():String {
            return _motherName;
        }

        public function set pId(value:Number):void {
            _pId = value;
        }
        public function get pId():Number {
            return _pId;
        }

        public function set provinceName(value:String):void {
            _provinceName = value;
        }
        public function get provinceName():String {
            return _provinceName;
        }

        public function set residen(value:String):void {
            _residen = value;
        }
        public function get residen():String {
            return _residen;
        }

        public function set vId(value:Number):void {
            _vId = value;
        }
        public function get vId():Number {
            return _vId;
        }

        public function set vaccinationDue(value:String):void {
            _vaccinationDue = value;
        }
        public function get vaccinationDue():String {
            return _vaccinationDue;
        }

        public function set vaccinationOverdue(value:String):void {
            _vaccinationOverdue = value;
        }
        public function get vaccinationOverdue():String {
            return _vaccinationOverdue;
        }

        public function set vaccines(value:String):void {
            _vaccines = value;
        }
        public function get vaccines():String {
            return _vaccines;
        }

        public function readExternal(input:IDataInput):void {
            _address = input.readObject() as String;
            _cId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _caretakerBirthYear = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _caretakerID = input.readObject() as String;
            _caretakerMobile = input.readObject() as String;
            _caretakerName = input.readObject() as String;
            _childCode = input.readObject() as String;
            _childId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _communeName = input.readObject() as String;
            _currentCaretaker = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _dId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _dateOfBirth = input.readObject() as Date;
            _districtName = input.readObject() as String;
            _fatherBirthYear = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _fatherID = input.readObject() as String;
            _fatherMobile = input.readObject() as String;
            _fatherName = input.readObject() as String;
            _fullName = input.readObject() as String;
            _gender = input.readObject() as Boolean;
            _listVaccines = input.readObject() as ListCollectionView;
            _locked = input.readObject() as Boolean;
            _motherBirthYear = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _motherID = input.readObject() as String;
            _motherMobile = input.readObject() as String;
            _motherName = input.readObject() as String;
            _pId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _provinceName = input.readObject() as String;
            _residen = input.readObject() as String;
            _vId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _vaccinationDue = input.readObject() as String;
            _vaccinationOverdue = input.readObject() as String;
            _vaccines = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_address);
            output.writeObject(_cId);
            output.writeObject(_caretakerBirthYear);
            output.writeObject(_caretakerID);
            output.writeObject(_caretakerMobile);
            output.writeObject(_caretakerName);
            output.writeObject(_childCode);
            output.writeObject(_childId);
            output.writeObject(_communeName);
            output.writeObject(_currentCaretaker);
            output.writeObject(_dId);
            output.writeObject(_dateOfBirth);
            output.writeObject(_districtName);
            output.writeObject(_fatherBirthYear);
            output.writeObject(_fatherID);
            output.writeObject(_fatherMobile);
            output.writeObject(_fatherName);
            output.writeObject(_fullName);
            output.writeObject(_gender);
            output.writeObject(_listVaccines);
            output.writeObject(_locked);
            output.writeObject(_motherBirthYear);
            output.writeObject(_motherID);
            output.writeObject(_motherMobile);
            output.writeObject(_motherName);
            output.writeObject(_pId);
            output.writeObject(_provinceName);
            output.writeObject(_residen);
            output.writeObject(_vId);
            output.writeObject(_vaccinationDue);
            output.writeObject(_vaccinationOverdue);
            output.writeObject(_vaccines);
        }
    }
}