/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ListChildrenPrintVO.as).
 */

package org.hil.core.model.vo {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class ListChildrenPrintVOBase implements IExternalizable {

        private var _children:ListCollectionView;
        private var _communeName:String;
        private var _dueDate:String;

        public function set children(value:ListCollectionView):void {
            _children = value;
        }
        public function get children():ListCollectionView {
            return _children;
        }

        public function set communeName(value:String):void {
            _communeName = value;
        }
        public function get communeName():String {
            return _communeName;
        }

        public function set dueDate(value:String):void {
            _dueDate = value;
        }
        public function get dueDate():String {
            return _dueDate;
        }

        public function readExternal(input:IDataInput):void {
            _children = input.readObject() as ListCollectionView;
            _communeName = input.readObject() as String;
            _dueDate = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_children);
            output.writeObject(_communeName);
            output.writeObject(_dueDate);
        }
    }
}