/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.hil.core.model.vo {

    [Bindable]
    [RemoteClass(alias="org.hil.core.model.vo.RegionVaccinationReportData")]
    public class RegionVaccinationReportData extends RegionVaccinationReportDataBase {
		
		private var _tBCG:String;
		private var _tVGBL24:String;
		private var _tVGBG24:String;
		private var _tDPT_VGB_Hib1:String;
		private var _tDPT_VGB_Hib2:String;
		private var _tDPT_VGB_Hib3:String;
		private var _tOPV1:String;
		private var _tOPV2:String;
		private var _tOPV3:String;
		private var _tMeasles1:String;
		
		public function get tBCG():String {
			return BCG + " (" + eBCG + ")";
		}
		
		public function get tVGBL24():String {
			return VGBL24 + " (" + eVGBL24 + ")";
		}

		public function get tVGBG24():String {
			return VGBG24 + " (" + eVGBG24 + ")";
		}
		
		public function get tDPT_VGB_Hib1():String {
			return DPT_VGB_Hib1 + " (" + eDPT_VGB_Hib1 + ")";
		}
		
		public function get tDPT_VGB_Hib2():String {
			return DPT_VGB_Hib2 + " (" + eDPT_VGB_Hib2 + ")";
		}
		
		public function get tDPT_VGB_Hib3():String {
			return DPT_VGB_Hib3 + " (" + eDPT_VGB_Hib3 + ")";
		}
		
		public function get tOPV1():String {
			return OPV1 + " (" + eOPV1 + ")";
		}
		
		public function get tOPV2():String {
			return OPV2 + " (" + eOPV2 + ")";
		}
		
		public function get tOPV3():String {
			return OPV3 + " (" + eOPV3 + ")";
		}
		
		public function get tMeasles1():String {
			return measles1 + " (" + eMeasles1 + ")";
		}
    }
}