/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (RegionVaccinationReportData.as).
 */

package org.hil.core.model.vo {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class RegionVaccinationReportDataBase implements IExternalizable {

        private var _BCG:Number;
        private var _DPT_VGB_Hib1:Number;
        private var _DPT_VGB_Hib2:Number;
        private var _DPT_VGB_Hib3:Number;
        private var _OPV1:Number;
        private var _OPV2:Number;
        private var _OPV3:Number;
        private var _VGBG24:Number;
        private var _VGBL24:Number;
        private var _amountOfFinish:Number;
        private var _childrenUnder1:Number;
        private var _eBCG:Number;
        private var _eDPT_VGB_Hib1:Number;
        private var _eDPT_VGB_Hib2:Number;
        private var _eDPT_VGB_Hib3:Number;
        private var _eMeasles1:Number;
        private var _eOPV1:Number;
        private var _eOPV2:Number;
        private var _eOPV3:Number;
        private var _eVGBG24:Number;
        private var _eVGBL24:Number;
        private var _measles1:Number;
        private var _protectedTetanusCases:Number;
        private var _reactionNormalCases:Number;
        private var _reactionSeriousCases:Number;
        private var _regionName:String;

        public function set BCG(value:Number):void {
            _BCG = value;
        }
        public function get BCG():Number {
            return _BCG;
        }

        public function set DPT_VGB_Hib1(value:Number):void {
            _DPT_VGB_Hib1 = value;
        }
        public function get DPT_VGB_Hib1():Number {
            return _DPT_VGB_Hib1;
        }

        public function set DPT_VGB_Hib2(value:Number):void {
            _DPT_VGB_Hib2 = value;
        }
        public function get DPT_VGB_Hib2():Number {
            return _DPT_VGB_Hib2;
        }

        public function set DPT_VGB_Hib3(value:Number):void {
            _DPT_VGB_Hib3 = value;
        }
        public function get DPT_VGB_Hib3():Number {
            return _DPT_VGB_Hib3;
        }

        public function set OPV1(value:Number):void {
            _OPV1 = value;
        }
        public function get OPV1():Number {
            return _OPV1;
        }

        public function set OPV2(value:Number):void {
            _OPV2 = value;
        }
        public function get OPV2():Number {
            return _OPV2;
        }

        public function set OPV3(value:Number):void {
            _OPV3 = value;
        }
        public function get OPV3():Number {
            return _OPV3;
        }

        public function set VGBG24(value:Number):void {
            _VGBG24 = value;
        }
        public function get VGBG24():Number {
            return _VGBG24;
        }

        public function set VGBL24(value:Number):void {
            _VGBL24 = value;
        }
        public function get VGBL24():Number {
            return _VGBL24;
        }

        public function set amountOfFinish(value:Number):void {
            _amountOfFinish = value;
        }
        public function get amountOfFinish():Number {
            return _amountOfFinish;
        }

        public function set childrenUnder1(value:Number):void {
            _childrenUnder1 = value;
        }
        public function get childrenUnder1():Number {
            return _childrenUnder1;
        }

        public function set eBCG(value:Number):void {
            _eBCG = value;
        }
        public function get eBCG():Number {
            return _eBCG;
        }

        public function set eDPT_VGB_Hib1(value:Number):void {
            _eDPT_VGB_Hib1 = value;
        }
        public function get eDPT_VGB_Hib1():Number {
            return _eDPT_VGB_Hib1;
        }

        public function set eDPT_VGB_Hib2(value:Number):void {
            _eDPT_VGB_Hib2 = value;
        }
        public function get eDPT_VGB_Hib2():Number {
            return _eDPT_VGB_Hib2;
        }

        public function set eDPT_VGB_Hib3(value:Number):void {
            _eDPT_VGB_Hib3 = value;
        }
        public function get eDPT_VGB_Hib3():Number {
            return _eDPT_VGB_Hib3;
        }

        public function set eMeasles1(value:Number):void {
            _eMeasles1 = value;
        }
        public function get eMeasles1():Number {
            return _eMeasles1;
        }

        public function set eOPV1(value:Number):void {
            _eOPV1 = value;
        }
        public function get eOPV1():Number {
            return _eOPV1;
        }

        public function set eOPV2(value:Number):void {
            _eOPV2 = value;
        }
        public function get eOPV2():Number {
            return _eOPV2;
        }

        public function set eOPV3(value:Number):void {
            _eOPV3 = value;
        }
        public function get eOPV3():Number {
            return _eOPV3;
        }

        public function set eVGBG24(value:Number):void {
            _eVGBG24 = value;
        }
        public function get eVGBG24():Number {
            return _eVGBG24;
        }

        public function set eVGBL24(value:Number):void {
            _eVGBL24 = value;
        }
        public function get eVGBL24():Number {
            return _eVGBL24;
        }

        public function set measles1(value:Number):void {
            _measles1 = value;
        }
        public function get measles1():Number {
            return _measles1;
        }

        public function set protectedTetanusCases(value:Number):void {
            _protectedTetanusCases = value;
        }
        public function get protectedTetanusCases():Number {
            return _protectedTetanusCases;
        }

        public function set reactionNormalCases(value:Number):void {
            _reactionNormalCases = value;
        }
        public function get reactionNormalCases():Number {
            return _reactionNormalCases;
        }

        public function set reactionSeriousCases(value:Number):void {
            _reactionSeriousCases = value;
        }
        public function get reactionSeriousCases():Number {
            return _reactionSeriousCases;
        }

        public function set regionName(value:String):void {
            _regionName = value;
        }
        public function get regionName():String {
            return _regionName;
        }

        public function readExternal(input:IDataInput):void {
            _BCG = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _DPT_VGB_Hib1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _DPT_VGB_Hib2 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _DPT_VGB_Hib3 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _OPV1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _OPV2 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _OPV3 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _VGBG24 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _VGBL24 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _amountOfFinish = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _childrenUnder1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eBCG = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eDPT_VGB_Hib1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eDPT_VGB_Hib2 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eDPT_VGB_Hib3 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eMeasles1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eOPV1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eOPV2 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eOPV3 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eVGBG24 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _eVGBL24 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _measles1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _protectedTetanusCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _reactionNormalCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _reactionSeriousCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _regionName = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_BCG);
            output.writeObject(_DPT_VGB_Hib1);
            output.writeObject(_DPT_VGB_Hib2);
            output.writeObject(_DPT_VGB_Hib3);
            output.writeObject(_OPV1);
            output.writeObject(_OPV2);
            output.writeObject(_OPV3);
            output.writeObject(_VGBG24);
            output.writeObject(_VGBL24);
            output.writeObject(_amountOfFinish);
            output.writeObject(_childrenUnder1);
            output.writeObject(_eBCG);
            output.writeObject(_eDPT_VGB_Hib1);
            output.writeObject(_eDPT_VGB_Hib2);
            output.writeObject(_eDPT_VGB_Hib3);
            output.writeObject(_eMeasles1);
            output.writeObject(_eOPV1);
            output.writeObject(_eOPV2);
            output.writeObject(_eOPV3);
            output.writeObject(_eVGBG24);
            output.writeObject(_eVGBL24);
            output.writeObject(_measles1);
            output.writeObject(_protectedTetanusCases);
            output.writeObject(_reactionNormalCases);
            output.writeObject(_reactionSeriousCases);
            output.writeObject(_regionName);
        }
    }
}