/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.hil.core.model.vo {
[Bindable]
[RemoteClass(alias="org.hil.core.model.vo.UserAuthentication")]
public class UserAuthentication extends UserAuthenticationBase {



    //check if user has the required role
    public function hasRole(p_role:String):Boolean
    {
        for (var i : int = 0; i < roles.length; i++)
        {

            var role : String = roles[i];
            if (p_role.toLowerCase() == role.toLowerCase())
                return true;
        }
        return false;
    }


    //check if user has at least one of required roles, do not need all required roles
    public function hasRoles(p_roles:Array):Boolean
    {

        for (var j:int = 0; j < p_roles.length; j++)
        {
            var p_role:String = p_roles[j];
            var result:Boolean = false;
            for (var i : int = 0; i < roles.length; i++)
            {
                var role : String = roles[i];
                if (p_role.toLowerCase() == role.toLowerCase())
                {
                    return true;

                }

            }

        }

        return false;
    }

}
}