/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (UserAuthentication.as).
 */

package org.hil.core.model.vo {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.hil.core.model.SystemUser;

    [Bindable]
    public class UserAuthenticationBase implements IExternalizable {

        private var _account:String;
        private var _expired:Boolean;
        private var _lock:Boolean;
        private var _roles:ListCollectionView;
        private var _user:SystemUser;

        public function set account(value:String):void {
            _account = value;
        }
        public function get account():String {
            return _account;
        }

        public function set expired(value:Boolean):void {
            _expired = value;
        }
        public function get expired():Boolean {
            return _expired;
        }

        public function set lock(value:Boolean):void {
            _lock = value;
        }
        public function get lock():Boolean {
            return _lock;
        }

        public function set roles(value:ListCollectionView):void {
            _roles = value;
        }
        public function get roles():ListCollectionView {
            return _roles;
        }

        public function set user(value:SystemUser):void {
            _user = value;
        }
        public function get user():SystemUser {
            return _user;
        }

        public function readExternal(input:IDataInput):void {
            _account = input.readObject() as String;
            _expired = input.readObject() as Boolean;
            _lock = input.readObject() as Boolean;
            _roles = input.readObject() as ListCollectionView;
            _user = input.readObject() as SystemUser;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_account);
            output.writeObject(_expired);
            output.writeObject(_lock);
            output.writeObject(_roles);
            output.writeObject(_user);
        }
    }
}