/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (VaccinationReportPrintVO.as).
 */

package org.hil.core.model.vo {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class VaccinationReportPrintVOBase implements IExternalizable {

        private var _communeName:String;
        private var _districtName:String;
        private var _provinceName:String;
        private var _regionId:Number;
        private var _regionName:String;
        private var _statistics:ListCollectionView;
        private var _sumAmountOfFinish:Number;
        private var _sumBCG:String;
        private var _sumChildrenUnder1:Number;
        private var _sumDPT_VGB_Hib1:String;
        private var _sumDPT_VGB_Hib2:String;
        private var _sumDPT_VGB_Hib3:String;
        private var _sumMeasles1:String;
        private var _sumOPV1:String;
        private var _sumOPV2:String;
        private var _sumOPV3:String;
        private var _sumProtectedTetanusCases:Number;
        private var _sumReactionNormalCases:Number;
        private var _sumReactionSeriousCases:Number;
        private var _sumVGBG24:String;
        private var _sumVGBL24:String;
        private var _timeData:String;
        private var _totalAmountOfFinish:Number;
        private var _totalBCG:String;
        private var _totalChildrenUnder1:Number;
        private var _totalDPT_VGB_Hib1:String;
        private var _totalDPT_VGB_Hib2:String;
        private var _totalDPT_VGB_Hib3:String;
        private var _totalMeasles1:String;
        private var _totalOPV1:String;
        private var _totalOPV2:String;
        private var _totalOPV3:String;
        private var _totalProtectedTetanusCases:Number;
        private var _totalReactionNormalCases:Number;
        private var _totalReactionSeriousCases:Number;
        private var _totalVGBG24:String;
        private var _totalVGBL24:String;

        public function set communeName(value:String):void {
            _communeName = value;
        }
        public function get communeName():String {
            return _communeName;
        }

        public function set districtName(value:String):void {
            _districtName = value;
        }
        public function get districtName():String {
            return _districtName;
        }

        public function set provinceName(value:String):void {
            _provinceName = value;
        }
        public function get provinceName():String {
            return _provinceName;
        }

        public function set regionId(value:Number):void {
            _regionId = value;
        }
        public function get regionId():Number {
            return _regionId;
        }

        public function set regionName(value:String):void {
            _regionName = value;
        }
        public function get regionName():String {
            return _regionName;
        }

        public function set statistics(value:ListCollectionView):void {
            _statistics = value;
        }
        public function get statistics():ListCollectionView {
            return _statistics;
        }

        public function set sumAmountOfFinish(value:Number):void {
            _sumAmountOfFinish = value;
        }
        public function get sumAmountOfFinish():Number {
            return _sumAmountOfFinish;
        }

        public function set sumBCG(value:String):void {
            _sumBCG = value;
        }
        public function get sumBCG():String {
            return _sumBCG;
        }

        public function set sumChildrenUnder1(value:Number):void {
            _sumChildrenUnder1 = value;
        }
        public function get sumChildrenUnder1():Number {
            return _sumChildrenUnder1;
        }

        public function set sumDPT_VGB_Hib1(value:String):void {
            _sumDPT_VGB_Hib1 = value;
        }
        public function get sumDPT_VGB_Hib1():String {
            return _sumDPT_VGB_Hib1;
        }

        public function set sumDPT_VGB_Hib2(value:String):void {
            _sumDPT_VGB_Hib2 = value;
        }
        public function get sumDPT_VGB_Hib2():String {
            return _sumDPT_VGB_Hib2;
        }

        public function set sumDPT_VGB_Hib3(value:String):void {
            _sumDPT_VGB_Hib3 = value;
        }
        public function get sumDPT_VGB_Hib3():String {
            return _sumDPT_VGB_Hib3;
        }

        public function set sumMeasles1(value:String):void {
            _sumMeasles1 = value;
        }
        public function get sumMeasles1():String {
            return _sumMeasles1;
        }

        public function set sumOPV1(value:String):void {
            _sumOPV1 = value;
        }
        public function get sumOPV1():String {
            return _sumOPV1;
        }

        public function set sumOPV2(value:String):void {
            _sumOPV2 = value;
        }
        public function get sumOPV2():String {
            return _sumOPV2;
        }

        public function set sumOPV3(value:String):void {
            _sumOPV3 = value;
        }
        public function get sumOPV3():String {
            return _sumOPV3;
        }

        public function set sumProtectedTetanusCases(value:Number):void {
            _sumProtectedTetanusCases = value;
        }
        public function get sumProtectedTetanusCases():Number {
            return _sumProtectedTetanusCases;
        }

        public function set sumReactionNormalCases(value:Number):void {
            _sumReactionNormalCases = value;
        }
        public function get sumReactionNormalCases():Number {
            return _sumReactionNormalCases;
        }

        public function set sumReactionSeriousCases(value:Number):void {
            _sumReactionSeriousCases = value;
        }
        public function get sumReactionSeriousCases():Number {
            return _sumReactionSeriousCases;
        }

        public function set sumVGBG24(value:String):void {
            _sumVGBG24 = value;
        }
        public function get sumVGBG24():String {
            return _sumVGBG24;
        }

        public function set sumVGBL24(value:String):void {
            _sumVGBL24 = value;
        }
        public function get sumVGBL24():String {
            return _sumVGBL24;
        }

        public function set timeData(value:String):void {
            _timeData = value;
        }
        public function get timeData():String {
            return _timeData;
        }

        public function set totalAmountOfFinish(value:Number):void {
            _totalAmountOfFinish = value;
        }
        public function get totalAmountOfFinish():Number {
            return _totalAmountOfFinish;
        }

        public function set totalBCG(value:String):void {
            _totalBCG = value;
        }
        public function get totalBCG():String {
            return _totalBCG;
        }

        public function set totalChildrenUnder1(value:Number):void {
            _totalChildrenUnder1 = value;
        }
        public function get totalChildrenUnder1():Number {
            return _totalChildrenUnder1;
        }

        public function set totalDPT_VGB_Hib1(value:String):void {
            _totalDPT_VGB_Hib1 = value;
        }
        public function get totalDPT_VGB_Hib1():String {
            return _totalDPT_VGB_Hib1;
        }

        public function set totalDPT_VGB_Hib2(value:String):void {
            _totalDPT_VGB_Hib2 = value;
        }
        public function get totalDPT_VGB_Hib2():String {
            return _totalDPT_VGB_Hib2;
        }

        public function set totalDPT_VGB_Hib3(value:String):void {
            _totalDPT_VGB_Hib3 = value;
        }
        public function get totalDPT_VGB_Hib3():String {
            return _totalDPT_VGB_Hib3;
        }

        public function set totalMeasles1(value:String):void {
            _totalMeasles1 = value;
        }
        public function get totalMeasles1():String {
            return _totalMeasles1;
        }

        public function set totalOPV1(value:String):void {
            _totalOPV1 = value;
        }
        public function get totalOPV1():String {
            return _totalOPV1;
        }

        public function set totalOPV2(value:String):void {
            _totalOPV2 = value;
        }
        public function get totalOPV2():String {
            return _totalOPV2;
        }

        public function set totalOPV3(value:String):void {
            _totalOPV3 = value;
        }
        public function get totalOPV3():String {
            return _totalOPV3;
        }

        public function set totalProtectedTetanusCases(value:Number):void {
            _totalProtectedTetanusCases = value;
        }
        public function get totalProtectedTetanusCases():Number {
            return _totalProtectedTetanusCases;
        }

        public function set totalReactionNormalCases(value:Number):void {
            _totalReactionNormalCases = value;
        }
        public function get totalReactionNormalCases():Number {
            return _totalReactionNormalCases;
        }

        public function set totalReactionSeriousCases(value:Number):void {
            _totalReactionSeriousCases = value;
        }
        public function get totalReactionSeriousCases():Number {
            return _totalReactionSeriousCases;
        }

        public function set totalVGBG24(value:String):void {
            _totalVGBG24 = value;
        }
        public function get totalVGBG24():String {
            return _totalVGBG24;
        }

        public function set totalVGBL24(value:String):void {
            _totalVGBL24 = value;
        }
        public function get totalVGBL24():String {
            return _totalVGBL24;
        }

        public function readExternal(input:IDataInput):void {
            _communeName = input.readObject() as String;
            _districtName = input.readObject() as String;
            _provinceName = input.readObject() as String;
            _regionId = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _regionName = input.readObject() as String;
            _statistics = input.readObject() as ListCollectionView;
            _sumAmountOfFinish = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _sumBCG = input.readObject() as String;
            _sumChildrenUnder1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _sumDPT_VGB_Hib1 = input.readObject() as String;
            _sumDPT_VGB_Hib2 = input.readObject() as String;
            _sumDPT_VGB_Hib3 = input.readObject() as String;
            _sumMeasles1 = input.readObject() as String;
            _sumOPV1 = input.readObject() as String;
            _sumOPV2 = input.readObject() as String;
            _sumOPV3 = input.readObject() as String;
            _sumProtectedTetanusCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _sumReactionNormalCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _sumReactionSeriousCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _sumVGBG24 = input.readObject() as String;
            _sumVGBL24 = input.readObject() as String;
            _timeData = input.readObject() as String;
            _totalAmountOfFinish = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _totalBCG = input.readObject() as String;
            _totalChildrenUnder1 = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _totalDPT_VGB_Hib1 = input.readObject() as String;
            _totalDPT_VGB_Hib2 = input.readObject() as String;
            _totalDPT_VGB_Hib3 = input.readObject() as String;
            _totalMeasles1 = input.readObject() as String;
            _totalOPV1 = input.readObject() as String;
            _totalOPV2 = input.readObject() as String;
            _totalOPV3 = input.readObject() as String;
            _totalProtectedTetanusCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _totalReactionNormalCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _totalReactionSeriousCases = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _totalVGBG24 = input.readObject() as String;
            _totalVGBL24 = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_communeName);
            output.writeObject(_districtName);
            output.writeObject(_provinceName);
            output.writeObject(_regionId);
            output.writeObject(_regionName);
            output.writeObject(_statistics);
            output.writeObject(_sumAmountOfFinish);
            output.writeObject(_sumBCG);
            output.writeObject(_sumChildrenUnder1);
            output.writeObject(_sumDPT_VGB_Hib1);
            output.writeObject(_sumDPT_VGB_Hib2);
            output.writeObject(_sumDPT_VGB_Hib3);
            output.writeObject(_sumMeasles1);
            output.writeObject(_sumOPV1);
            output.writeObject(_sumOPV2);
            output.writeObject(_sumOPV3);
            output.writeObject(_sumProtectedTetanusCases);
            output.writeObject(_sumReactionNormalCases);
            output.writeObject(_sumReactionSeriousCases);
            output.writeObject(_sumVGBG24);
            output.writeObject(_sumVGBL24);
            output.writeObject(_timeData);
            output.writeObject(_totalAmountOfFinish);
            output.writeObject(_totalBCG);
            output.writeObject(_totalChildrenUnder1);
            output.writeObject(_totalDPT_VGB_Hib1);
            output.writeObject(_totalDPT_VGB_Hib2);
            output.writeObject(_totalDPT_VGB_Hib3);
            output.writeObject(_totalMeasles1);
            output.writeObject(_totalOPV1);
            output.writeObject(_totalOPV2);
            output.writeObject(_totalOPV3);
            output.writeObject(_totalProtectedTetanusCases);
            output.writeObject(_totalReactionNormalCases);
            output.writeObject(_totalReactionSeriousCases);
            output.writeObject(_totalVGBG24);
            output.writeObject(_totalVGBL24);
        }
    }
}